version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: lein with-profile +test deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Check code style > kibit
          command: lein kibit

      - run:
          name: Check code style > cljfmt
          command: lein with-profile +cljfmt cljfmt check

      - run:
          name: Check code style > eastwood
          command: lein with-profile +eastwood eastwood

      - run:
          name: Run unit tests
          command: lein with-profile test cloverage --codecov

      - run:
          name: Send test coverage report
          command: bash <(curl -s https://codecov.io/bash)